#' Extract Rainfall Threshold and Comparison Operator
#'
#' This function parses a rainfall condition string of the form `"(rainfall >= 40)"`
#' to extract both the comparison operator (e.g., `>=`) and the threshold value (e.g., `40`).
#' It is used to identify how rain days or extreme rainfall conditions are defined
#' in the metadata generated by R-Instat.
#'
#' @param definitions_in_raw A named list containing raw metadata definitions, typically
#'   generated by `get_r_instat_definitions()` on the unaggregated data.
#' @param rainfall_column The name of the variable in `definitions_in_raw` that contains the
#'   rain condition (e.g., `"extreme_rain"` or `"count"`).
#' @param list_name Optional. If provided, the result will be nested in a named list with this key
#'   (e.g., `list(extreme_rain = list(...))`). If `NULL` (default), returns a flat list with
#'   elements `sign` and `threshold`.
#'
#' @return A list containing:
#' \describe{
#'   \item{sign}{The extracted comparison operator (e.g., `>=`, `<`, `==`).}
#'   \item{threshold}{The extracted numeric threshold as a character string (e.g., `"40"` or `"-12.5"`).}
#' }
#' If `list_name` is supplied, the result is nested inside a named list.
#' If the required structure or value is missing, both elements default to `NA`.
#'
#' @examples
#' defs <- list(extreme_rain = list(rain_day = list(NULL, "(rainfall >= 40)")))
#'
#' # Returns: list(sign = ">=", threshold = "40")
#' get_rain_counts(defs, "extreme_rain")
#'
#' # Returns: list(extreme_rain = list(sign = ">=", threshold = "40"))
#' get_rain_counts(defs, "extreme_rain", "extreme_rain")
#'
#' @export
get_rain_counts <- function(definitions_in_raw = NULL,
                            rainfall_column = "extreme_rain",
                            list_name = NULL) {
  result <- list(sign = NA, threshold = NA)
  
  if (!is.null(definitions_in_raw) && !is.null(rainfall_column)) {
    definition <- definitions_in_raw[[rainfall_column]]
    definition_rain_day_value <- definition$rain_day[[2]]
    
    # Extract components
    result$sign <- sub(".*\\s([<>]=?|==|!=)\\s.*", "\\1", definition_rain_day_value)
    result$threshold <- sub(".*\\s([<>]=?|==|!=)\\s*(-?\\d*\\.?\\d+)\\s*\\)?", "\\2", definition_rain_day_value)
  }
  
  if (!is.null(list_name)) {
    return(setNames(list(result), list_name))
  } else {
    return(result)
  }
}
